### PR TITLE
Adds system library

### PR DESCRIPTION
**Pull request by ryanmrichard**
# Description of Pull Request

We had expressed interest in having a library of molecules that accompany Pulsar so that we didn't have to copy/paste existing ones and/or struggle to find geometries for testing purposes.  This PR is my take on a start to one.  Assuming the PR is liked, additional molecules could be added as part of other PRs, *i.e.* I don't want to keep this open until it is filled out.

I purpose a directory structure:
```
+--Pulsar/Install/Root
   +--lib
      +--pulsar
         +--basis
         +--modules
         +--systems
            +--molecule_name
               +--geom_descriptor
                  +--level_of_theory.py
```
In more detail:
- molecule_name: This would be something quite generic like water, ammonia, CH4, *etc.*
- geom_descriptor: This would be a descriptor of the isomer type, cluster size, relative orientation, *etc.*
   - Some examples: dimer, cis/trans, protenated (for amino acids since biochemists consider molecules with different chemical formulas to be the same molecule...), space_group, polymorph name, *etc.*
- level_of_theory.py: This would be the Python module that returns the geometry when called. It would be named after the level of theory used to generate the structure.
  - Some examples mp2_aug_cc_pvdz, TIP5P, experimental, *etc.*

As for the guts of the Python module:
```.py
import pulsar as psr
def make_system():
    """More details on how the geom was obtained and references if available"""   
    return psr.make_system(""Cartesian coordinates go here""")
```

I can then envision two ways of using this:
```.py
from psr.systems.molecule_name.geom_descriptor.level_of_theory import make_system

wfn=psr.Wavefunction()
wfn.system=make_system()
```

or modifying the usual `make_system` to take a relative path and it would go retrieve the molecule from
the systems library:
```.py
wfn=psr.Wavefunction()
wfn.system=psr.make_system("""molecule_name.geom_descriptor.level_of_theory""")
```

I am assuming all geometries in this library would be either experimental or optimized with some level of theory (even if it's the UFF, which I think is what most molecule drawers use to clean the structure up) and that we wouldn't have things like "Billy's rendition of a protein" (although Billy should feel free to put his protein in his own Pulsar installation, just not the GitHub repo...)

### CODE REVIEW

**Comment by ryanmrichard** [comment]
General note:  If accepted squash and merge because Git didn't pick up on the directory rename.

**Comment by bennybp** [comment]
I'm liking the idea. I imagine the core would contain the most common molecules, and then may another package with a whole bunch? I wonder if there's one that's publicly accessibly (like cccbdb, but downloadable all at once).

For making the system from an input, I would think maybe another function (`load_reference_system` or something shorter) would be nice to prevent overloading the python function too much.

Any big advantages to using make_system rather than just storing something xyz-like and then the new function just reading that? I suppose it can come in handy with symmetry, periodic, etc.

**Comment by ryanmrichard** [comment]
In reverse order, the reason for a function was, like you guessed, geared more towards complicated systems like crystals.  Here xyz-like falls apart because there's no standard way to give lattice constants or to specify whether something is in fractional coordinates or Cartesians, etc.  As long as its a function then we can have it give back a `pulsar::System` instance.

Yeah, it's a C++ habit of mine to overload the crap out of a function if I intend to use it in the same context as another.  You're right `load_reference_system` is probably a better choice.

cccbdb came to mind for me as well.  Worst case scenario could write a script to skim it.  Psi4 uses PubChem, but I don't like the idea of using an internet connection to get the molecules.  I like the idea of having a separate repo or something to prevent it from getting ridiculous in size.

**Comment by keipertk** [comment]
For a "core" set of molecules distributed with the Pulsar repo primarily for testing purposes, you might consider it useful to include molecule "class" in your directory structure. See here:

https://github.com/nutjunkie/IQmol/tree/master/share/fragments/Molecules

(Unfortunately those are just .xyz and I couldn't find data for geom_descriptor or level of theory)

I could see this being helpful when you want to easily test a varied set of molecules (pick one or two from each directory), or test a few particular types of molecules.

**Comment by ryanmrichard** [comment]
@keipertk this looks awesome.  Even if they don't have levels of theory, at least I can easily make some tests that are not just water molecules.  It's also good to know IQMol is on GitHub.

I am not sold on the directory structure I came up with.  It's already too nested for my liking.  The ability to tag molecules would be interesting, although I also don't want to end up in full blown cheminformatics.

**Comment by ryanmrichard** [comment]
I presume we are sold on the system's install directory location (level with the basis dir).  I am rethinking the level of theory part.  The point of this library would be to give you some starting structures, not to keep a catalog of computations that have been run (although a user is free to do that if they so choose).  Perhaps the latter could be handled by this additional library repo.  Also in the additional repo we could then start going down the rabbit hole of cheminformatics by storing the structures in a sort of  database complete with tags.  The use of a database would inevitably bring in additional dependencies and is why I would not want it as part of the core.  I can also then foresee this repo being of use to other projects for things like data mining, rapid throughput screening, *etc.* (in fact I find it somewhat hard to believe that such a database doesn't already exist on GitHub, although as a disclaimer I have not looked hard).

With the above said I'm going to recommend a `system` directory structure of:
```
+--system
     +--water_dimer.py
     +--water_trimer.py
     +--ethane.py
     +--methane.py
      ...
```

Within each of these `.py` files would then be a function `load_ref_system` that returns the `pulsar::System` instance.  

I like @keipertk's suggestion of adding classes, but think it would work better in a database environment where you could tag methanol as being an organic, alcohol, solvent and then query the database for all molecules with a tag.  I think trying to setup a directory structure that reflects this is going to only lead to headaches as, in my opinion, things like an amino acid can fall under several categories (aromatic, amino acid, *etc.*) and people will then inevitably start bickering over which directory to put it in.

**Pull request merged**
