### PR TITLE
Nmerinfo

### PR DESCRIPTION
**Pull request by ryanmrichard**
Updates Pybind11 to use @loriab's config file.  Also sneaks in revamped cache documentation.

### CODE REVIEW

**Comment by bennybp** [comment]
Ha I was just doing something similar. This might be a bit of a mess

**Comment by ryanmrichard** [comment]
The changes are deceptively large because the old pybind11 is deleted.  Aside from that there's not a ton of changes in this PR.  There's some tweaks to exports of Space and CacheData to use pybind11::metaclass, and the new documentation (and I guess a wavefunction test, but I thought I checked that in before).

**Comment by bennybp** [comment]
I just made a local commit that does some similar things. It converts pybind11, bphash, and bpprint to be retrieved via git in the external_project add. It also adds c++14 flags and whatnot. Any objection to those?

**Comment by ryanmrichard** [comment]
No objections here.  You should feel free to change LibTaskForce to that too if you want (I think it's the only git submodule we still have).

**Comment by bennybp** [comment]
Ok done. I will have to manually merge some of the changes of this PR into mine. It shouldn't be much of a problem, since we did do some of the same thing

**Comment by loriab** [comment]
I'll check in psi4's update to pb11 head later today. FYI, I started hacking at `psi4Config.cmake` and standardized some variable names– partial below. Haven't exported a psi4 target yet, which I think is what you're using sometimes. If you really needed driver_DIR and the others, let me know.

```
# location of script psi4
set(${PN}_EXECUTABLE "${PACKAGE_PREFIX_DIR}/@CMAKE_INSTALL_BINDIR@/psi4")

# directory containing psi4/psi4-dec.h
set(${PN}_INCLUDE_DIR "${PACKAGE_PREFIX_DIR}/@CMAKE_INSTALL_INCLUDEDIR@")

# location of psi4/core.so
set(${PN}_LIBRARY "${PACKAGE_PREFIX_DIR}/@CMAKE_INSTALL_LIBDIR@@PYMOD_INSTALL_LIBDIR@/psi4/@PYTHON_MODULE_PREFIX@core.so")

# presence of external addons
macro(psi4_component name on)
    if(${on})
        set(${PN}_${name}_FOUND 1)
        list(APPEND ${PN}_FOUND_COMPONENTS ${name})
    endif()
endmacro()

#psi4_component(ambit @ENABLE_AMBIT@)
psi4_component(chemps2 @ENABLE_CheMPS2@)
psi4_component(dkh @ENABLE_dkh@)
psi4_component(erd @ENABLE_erd@)
psi4_component(gdma @ENABLE_gdma@)
#psi4_component(gtfock @ENABLE_GTFock@)
#psi4_component(pcmsolver @ENABLE_PCMSolver@)

foreach(_comp ${${PN}_FIND_COMPONENTS})
    if(${${PN}_${_comp}_FOUND})
    else()
        if(NOT CMAKE_REQUIRED_QUIET)
            message(STATUS "${PN} missing requested component: ${_comp}")
        endif()
    endif()
endforeach()

check_required_components(${PN})

if(NOT CMAKE_REQUIRED_QUIET)
    message(STATUS "Psi4 script:  ${${PN}_EXECUTABLE}")
    message(STATUS "Psi4 headers: ${${PN}_INCLUDE_DIR}")
    message(STATUS "Psi4 library: ${${PN}_LIBRARY}")
    message(STATUS "Psi4 components: ${${PN}_FOUND_COMPONENTS}")
    message(STATUS "Python executable: @PYTHON_EXECUTABLE@")
endif()



set(PSI4_INCLUDE_DIRS
    ${psi4_INCLUDE_DIR}
    @PYTHON_INCLUDE_DIR@
    ${psi4_INCLUDE_DIR}/@RELATIVE_PYBIND11_INCLUDE_DIR@
)


function(add_psi4_plugin TARGET SOURCES)
    # remove ${TARGET} from ${ARGV} to use ${ARGV} as ${SOURCES}
    list(REMOVE_AT ARGV 0)

    add_library(${TARGET} MODULE ${ARGV})
    target_include_directories(${TARGET} SYSTEM PRIVATE ${PSI4_INCLUDE_DIRS})
    target_link_libraries(${TARGET} ${core_LIBRARY})
    set_target_properties(${TARGET} PROPERTIES
                          PREFIX ""
                          COMPILE_FLAGS "-std=c++@CMAKE_CXX_STANDARD@")
    if (APPLE)
        set_target_properties(${TARGET} PROPERTIES LINK_FLAGS "-undefined dynamic_lookup")
    endif()

    # Add additional properties to the "make clean" to delete *.pyc
    set_directory_properties(PROPERTIES ADDITIONAL_MAKE_CLEAN_FILES "*.pyc")
endfunction(add_psi4_plugin)
```

**Comment by ryanmrichard** [comment]
At the moment the only things I use from the config file are:
~~~cmake
get_target_property(PSI4_CORE psi4 INTERFACE_LINK_LIBRARIES)
get_filename_component(PSI4_LIBRARY_DIR ${PSI4_CORE} DIRECTORY)
get_filename_component(PSI4_LIBRARY_DIR ${PSI4_LIBRARY_DIR} DIRECTORY)
~~~

**Comment by loriab** [comment]
Ok, we'll have to see. As a variable name, PSI4_CORE is gone, and I'm not sure what the difference in those last two lines is. And everything psi4 is lc.

**Comment by ryanmrichard** [comment]
I wasn't using your PSI4_CORE variable, I was just using the INTERFACE_LINK_LIBRARIES property of the psi4 target.  The rest of those cmake commands just move up two directories from the .so, which is the directory that needs appended to PYTHONPATH to find the Psi4 module.

**Comment by ryanmrichard** [comment]
@bennybp, As @loriab just brought up in RL pybind11 will handle finding Python, do we want to just rely on it to do that?

**Comment by bennybp** [comment]
Possibly, although we still have to have the options at the top level.

I think my weekend project is going to be to polish the build system (again). I want to try to simplify all of these variables that are being passed through externalproject_add and see if I can reduce the duplicate code a bit. Now that I've added 3 more (CMAKE_CXX_STANDARD, CMAKE_CXX_EXTENSIONS, and CMAKE_POSITION_INDEPENDENT_CODE), it's a bit verbose

**Comment by ryanmrichard** [comment]
@bennybp, which commit of pybind11 do you want to support?  The newest one breaks Psi4 as well as us (this PR fixes those breaks though).

**Comment by bennybp** [comment]
What does it break for us and psi4? It seems to be ok for me on the pulsar side

**Comment by ryanmrichard** [comment]
It forces us to insert `pybind11::metaclass()` into the `pybind11::class_` constructor when we export static members/methods and for Psi4 a similar requirement of adding `pybind11::buffer_protocol()` to the constructor when your object defines a buffer protocol.

**Comment by ryanmrichard** [comment]
BTW. It shows up at runtime not compile time.

**Comment by bennybp** [comment]
Yeah I did see that. I fixed the instance in the cache classes by changing them back to enums. I imagine fixing those is psi4 might be tricky?

**Comment by ryanmrichard** [comment]
It's no more tricky then it was for us, but it's more the fact that this is an API breaking change.  So we have to stay to one side or the other of it.

**Comment by bennybp** [comment]
I'm basically trying to stay up to date with pybind11 at least until they reach 2.0 (and I assume psi4 would like that as well?).

**Comment by ryanmrichard** [comment]
Psi4 is using c79e435e00fd4fb49817a87c3c2b2647482c077b at the moment, which is the one right before the API break.  I'd vote for this until Pybind11 gets to 2.0 or another bug gets in the way.

**Comment by ryanmrichard** [comment]
Basically I'd rather handle all the API breaks at once in case there are more.

**Comment by bennybp** [comment]
Oh that should be fine. I thought the metaclass stuff was further back than that. I will change it in my copy, which I will merge the other changes from this PR into (although that needs my PR on LTF)

**Comment by bennybp** [comment]
The most important commit (with your documentation) should have been included in the build_polish merge. But you can double check. Otherwise, this should be superseded by that PR.

**Pull request closed without merging**
