### PR TITLE
Parallel Overhaul

### PR DESCRIPTION
**Pull request by ryanmrichard**
As mentioned in my Pulsar-Meta PR, I'm playing with how the parallelism gets done.

At the moment this PR does:

- [x] Removes LTF
- [ ] Makes parallelism a module
- [ ] Documents the new parallelism
- [ ] Provides unit tests for parallel capabilities

# Overall Plan
For the most part I think of parallelism as having two parts: data-based and task-based.  This PR exclusively focuses on the latter.  To that end, I would like to make a new module base that I am tentatively calling `Parallelizer` (try saying that 3x fast).  As I see it, there are really three task-based operations:

1. for
2. foreach 
3. reduce

For and reduce are somewhat naturally implemented in terms of functors/lambdas. Foreach is naturally implemented in terms of a container and a functor/lambda that takes an instance of whatever is stored in the container.  Unfortunately, foreach and reduce quasi-require templates...

I think we will also need a concept of atomics.

# Purposed APIs

## for

```.cpp
//Type of a lambda to be used by parallel_for.  Argument is the index value
using for_fxn=void(*)(size_t);
//Actual parallel_for call.  Argument is the lambda to run.  Non-const to allow modifying state
void parallel_for(for_fxn& fxn_2_run);
```

### CODE REVIEW

**Comment by ryanmrichard** [comment]
On second thought, although it would be nice for parallelism to be a module, maybe it's not that important.  The fact that foreach/reduce would have to be templated to be done correctly is my main qualm.  Templating could be replaced with type-erasure, but it's not clear to me that can be done without significant performance penalties.  I have to think about this...

**Comment by bennybp** [comment]
Yeah I have a feeling that most (super)modules would have their own way of parallelizing things.

I’ve done this kind of runtime parallelism before, and it worked ok, but wasn’t very flexible.

**Comment by ryanmrichard** [comment]
I am thinking you are right so assuming you are okay with the changes on this and Meta's PR then I think these PRs are good to go.

**Comment by ryanmrichard** [comment]
This PR doesn't do much besides get rid of LTF.  I'm going to merge it so I can give easier instructions to a colleague.

**Pull request merged**
