### PR TITLE
Python Checkpointing

### PR DESCRIPTION
**Pull request by ryanmrichard**
# Description of Pull Request

The goal of this PR is to allow checkpointing of Python objects, be it from true Python or Pybind11 wrapped stuff.  It also adds to the documentation of affected classes.

Todos:
- [x] Successfully pickle/unpickle in C++
- [x] Add (working) tests for all affected classes/functions:
  - [x] CacheData
  - [x] CacheMap
  - [x] Serialization
  - [x] ModuleCreationFuncs
  - [x] ModuleManager
  - [x] Checkpoint
- [x] Make major Pulsar classes pickleable
  - [x] Wavefunction
  - [x] System

### CODE REVIEW

**Comment by ryanmrichard** [comment]
Any thoughts on the following?

I am trying to write a test for the CacheData class from Python.  No constructor is exposed to Python.  The natural way around this is something like:
~~~.cpp
CacheData get_cachedata();

PYBIND11_PLUGIN(testing_exports){
    pybind11::module mtop("testing_exports", "Functions to test from Python");
    mtop.def("get_cachedata",&get_cachedata);
    return mtop.ptr();
}
~~~

Let's call that file `testing_exports.cpp`.  We used used to have (I recall these files existing at one point, but can't seem to find them) a directory structure something like:

~~~
Pulsar-Core
+-- pulsar
     +-- datastore
           +-- testing_exports.cpp
+-- build
+-- test
      +-- datastore
~~~

Seeing as how these functions are not meant as part of the main API I don't think they really belong there.  So what I wanted to do is:
~~~
Pulsar-Core
+-- pulsar
     +-- datastore
+-- build
+-- test
      +-- datastore
            +-- testing_exports.cpp
~~~

and install it to:

~~~
Pulsar-Core
+-- pulsar
     +-- datastore
+-- build
      +-- test_stage
           +-- datastore
                 +-- testing_exports.so
                 +-- TestCacheMap.py
+-- test
      +-- datastore
            +-- testing_exports.cpp
~~~

Then in `TestCacheMap.py`
~~~.py
import pulsar as psr
#import testing_exports <-------------doesn't work (no module named testing_exports)
#import .testing_exports <------------doesn't work (can't relative import)
~~~

I include this part because I think this is ideal, but can't seem to make Python's poorly documented import functionality work with it.  Instead I think I will have to settle for:
~~~
Pulsar-Core
+-- pulsar
     +-- datastore
+-- build
      +-- test_stage
           +-- datastore
                 +-- testing_exports
                       +-- __init__.py
                       +-- testing_exports.so
                 +-- TestCacheMap.py
+-- test
      +-- datastore
            +-- testing_exports.cpp
~~~

and then the first import should work.

**Comment by bennybp** [comment]
I've done the first way before and I don't remember there being any problems. I've always been able to import an so from the current directory.

http://stackoverflow.com/questions/6576351/how-to-import-module-from-current-non-default-directory (although that's python 2.7)

**Comment by ryanmrichard** [comment]
You're probably right.  The subdirectory thing isn't working either... keeps claiming the darn module doesn't exist grrrrrrrrrrr

**Comment by ryanmrichard** [comment]
Yep, my Python path somehow no longer includes the current directory.  WTF?  My entire MM code has its Python scripts in the same directory and this was never a problem...

Putting the so in the same directory gives me "ImportError: dynamic module does not define module export function (PyInit_testing_functions)".  The only way I know to get past this is the subdirectory and `__init__.py` script

**Comment by bennybp** [comment]
You have to make sure that the filename is the same as what goes in PYBIND11_PLUGIN(). Maybe you have testing_exports in one place and testing_functions in another?

**Comment by ryanmrichard** [comment]
You are so smart.  Yep.  I alternated between "test" and "testing"...

**Comment by bennybp** [comment]
Only because I've made that mistake more than a few times...

**Comment by ryanmrichard** [comment]
I love that none of the solutions I found on the internet for that error were even remotely near that...

**Comment by loriab** [comment]
https://pybind11.readthedocs.io/en/master/faq.html#importerror-dynamic-module-does-not-define-init-function

**Comment by ryanmrichard** [comment]
That's for does not define *init* function my error was does not define *export* function

**Comment by loriab** [comment]
true

**Comment by ryanmrichard** [comment]
So all I have left to do is to test checkpointing of the Python objects.  The current API requires modules for this to work.  How do you feel about pulling the part of `ModuleManager::load_module_from_minfo` working with the `ModuleCreationFuncs`  instance into a separate function `ModuleManager::load_module_from_mcfs`.  Then we can define a module and a corresponding set of ModuleCreationFuncs in a .cpp or .py file and use the resulting module in the same file.  If approved, I vote we call such modules lambda modules as they are somewhat in the spirit of lambda functions.

If not approved, I still think we need this ability so that users can tweak algorithms without having to establish a full fledged supermodule.

**Comment by bennybp** [comment]
I think that should work. Should I do that or are you going to take a crack at it

**Comment by ryanmrichard** [comment]
I was going to take a crack at it.

**Comment by ryanmrichard** [comment]
@bennybp disregard the bricking of the MM class I can't seem to reproduce it today.

**Comment by ryanmrichard** [comment]
@bennybp I'm declaring this r2g.  This includes some flavor of your PR so I figure I'll wait for yours to go through and then rebase (?).  Hopefully that will shorten the change log a bit so that you can look at my changes easier.

**Comment by bennybp** [comment]
If you want to try rebasing, go ahead. There will be some minor conflicts with some CMake. Let me know if you don't understand my changes.

**Comment by ryanmrichard** [comment]
I'll try it in a bit, I'm working on a `is_pickleable` function at the moment because it took me all of 3 seconds since declaring this r2g to get burned by that...

**Comment by ryanmrichard** [comment]
Should be easier to look at now.  I'm moving this back to WIP until I can pickle all the classes I need to be able to pickle

**Comment by ryanmrichard** [comment]
I'm having a lot of trouble getting the tests to work again now.  As you said the RPaths for the meta-package's install aren't being found for the staged tests.  I thought this would do it:

```cmake
#in CTestMacros.cmake
STRING(REPLACE ";" ":" CMAKE_PREFIX_PATH_STR ${CMAKE_PREFIX_PATH})
SET(CTEST_ENVIRONMENT "LD_LIBRARY_PATH=:${CMAKE_PREFIX_PATH_STR}")
```

,but `printenv` shows that it is just my usual `LD_LIBRARY_PATH` value (set by Intel's script in my .bashrc; which grepping their scripts they never overwrite the value).

**Comment by bennybp** [comment]
Which path does it say it is missing? One of your preinstalled dependencies?

On January 19, 2017 7:06:58 PM EST, Ryan Richard <notifications@github.com> wrote:
>I'm having a lot of trouble getting the tests to work again now.  As
>you said the RPaths for the meta-package's install aren't being found
>for the staged tests.  I thought this would do it:
>
>```cmake
>#in CTestMacros.cmake
>STRING(REPLACE ";" ":" CMAKE_PREFIX_PATH_STR ${CMAKE_PREFIX_PATH})
>SET(CTEST_ENVIRONMENT "LD_LIBRARY_PATH=:${CMAKE_PREFIX_PATH_STR}")
>```
>
>,but `printenv` shows that it is just my usual `LD_LIBRARY_PATH` value
>(set by Intel's script in my .bashrc; which grepping their scripts they
>never overwrite the value).
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pulsar-chem/Pulsar-Core/pull/30#issuecomment-273938586

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ryanmrichard** [comment]
Memwatch.so

**Comment by bennybp** [comment]
Ahh I left that to be a bit manual (I can explain that sometime).

Pass `-DCMAKE_INSTALL_RPATH=/path/to/dependencies/lib` to the Pulsar-Core project. That should fix it for this particular case. (just make sure it is to the lib directory, not just the prefix).

BTW, the CTEST_ENVIRONMENT this is kind of useless, from what I understand. Something about script mode in ctest.

**Comment by ryanmrichard** [comment]
OK.  I got the tests running again for the core.  I see you changed the install directory structure.  I added a variable `PULSAR_MODULE_DIR=install/path/lib/pulsar/modules` so that as we install super modules something like:
```
+---install_root
    +---lib
        +---pulsar
            +---modules
                +---pulsar
                +---standard_modules
                +---pulsar_psi4
                +---other_supermodules
```

**Comment by ryanmrichard** [comment]
variable has been added to `pulsarConfig.cmake`

**Comment by bennybp** [comment]
Yes that is the layout I was going for, at least for a standard installation. Modules can be anywhere, of course. There may be some things that go in <install_root>/lib/pulsar also (basis sets? a bin directory with some other stuff?)

**Comment by ryanmrichard** [comment]
Wow that last part was a lot harder than I anticipated; despite how simple the solution looks.  Anyways, this is more or less ready to go.  I added two functions to `Serialization.hpp`:
~~~.cpp
template<typename T>
pybind11::bytes __getstate__(const T& obj);

template<typename T>
void __setstate__(T& obj,const pybind11::bytes& b);
~~~

that respectively contain the implementation for pickleing and un-pickleing a C++ class, that has been exported to Python via pybind11 bindings, and has been instantiated in Python (or at the least put into the cache from Python).  They simply defer to the object's Cereal serialization routines.  They are then used in the pybind11 exports of the class like:

~~~.cpp
.def("__getstate__",[](const T& obj){return __getstate__(obj);})
.def("__setstate__",[](T& obj,const pybind11::bytes& b){__setstate__(obj,b);})
~~~

I'm not sure if the lambda is really needed or if I was just doing something wrong when I tried to just use the function.

**Pull request merged**
