### PR TITLE
WIP: Having a go at HF

### PR DESCRIPTION
**Pull request by ryanmrichard**
This branch includes my modifications required to get HF working in terms of LibInt2.

At the moment the changes are:

1. `OneElectronIntegral` and `TwoElectronIntegral` now return the integrals instead of the number of integrals.
    - Returned integrals are a null pointer if they were screened out
2. Adds a little function for swapping out a subsystem of a system (missed this in my last PR)
3. `CppTester` and `PyTester` now have a function `test_double_vector` for comparing all elements of a
    vector
3. `OneElectronIntegral` is now `TwoCenterIntegral`
4. `TwoElectronIntegral` is now `FourCenterIntegral`
5. Adds a `ThreeCenterIntegral`
6. Adds aug-cc-pvdz-ri basis set
7. Copies ForceManII's auto-doc scripts and Travis build script over (they are not hooked-up yet)
8. Renames `OneElectronMatrix` to `MatrixBuilder`
9. Introduces a polymorphich `my_hash` method to some module bases (eventually needs to roll out to all)

### CODE REVIEW

**Comment by bennybp** [comment]
The issue with renaming to TensorFactory is that the calculate function is a virtual function, and the rank (and type) are template parameters. So you would likely have to split out different base classes for different ranks and types anyway. Unless the TensorFactory class itself was templated...although the syntax for getting a module from the module manager gets a little hairy.

For returning a map, yeah, we would have to standardize the names of the returned tensors (which might be ok). Or at least the caller has to iterate over the map. The other option is to have different keys in the module manager for the same module with a different option (for which to calculate), and then have the module use the cache.

Returning a map can be a little complicated as well. What if a packages builds 2J-K together but the caller requests J and K separately? Or vice versa?

Point 5 is still completely up in the air, and should be something I bring up at the workshop next month. It would be nice if tensor libraries could take a callback for computing some elements, although that gets tricky with integrals.

And I'm still not sure about the integral pointer issue, but I will have to think about that more

**Comment by ryanmrichard** [comment]
The more I play with it, the more I think you are right on that we'll have to split off base classes anyways.

In a perfect world we would implement some logic that goes like:
- need F check cache, if not there
- F is H+G
  - Check for H, if not there build it
  - need G check cache, if not there
     - G is 2J-K check cache, if not there
        - is 2J there, if not
          - is J there, if not build it
        - is K there, if not build it
To some extent this would require minimally a module for F, H+G, H, G, 2J-K, 2J, J, and K.  This is just for HF, can you imagine CCSD...At the same time this is also exactly what expression templates do.  I think this means we inevitably will need to either firmly adopt a tensor library and rely on its ability to do such manipulations itself, or implement all of this logic ourselves (we would then rely on the underlying tensor library for the actual operations).  

Returning step-wise like this would also eliminate the need for the map return as each TensorFactory would return a single Tensor.

On computing some elements I think that is possible for both Eigen's tensor implementation and TiledArray.  In both cases I think you need to make a custom "tile" functor.

**Comment by ryanmrichard** [comment]
So I now have a working SCF module.  My implementation uses these `OneElectronMatrix` modules in a manner similar to the above post:

- F(OneElectronMatrix)
  - H(OneElectronMatrix)
    - T(OneElectronMatrix)
    - V(OneElectronMatrix)
  - G(OneElectronMatrix)
    - JK(OneElectronMatrix)

My two cents at this point (subject to change, but wanted to document):

- There's just something that still bothers me about the name `OneElectronMatrix` especially since it is not returning a `IrrepSpinMatrix` instance.  I am leaning towards MatrixFactory...
- I presume passing the key to `OneElectronMatrix` is a hold over from before we somewhat standardized passing keys as options?
- In the same vein, does it make sense to explicitly pass the basis sets to `OneElectronMatrix` and the two integral classes? Or should that also move to an option like `BASIS_SET_KEYS` or something?

I want to do UHF before I commit to anything and see how spin should play in to this.

**Comment by bennybp** [comment]
Yes I agree `OneElectronMatrix` is a bit awkward. `MatrixBuilder` might be better, since Factory is a bit of an overloaded term in C++. But that's only slightly better

Agree on the Electron->Center change. I do think that's a lot better.

**Comment by ryanmrichard** [comment]
@bennybp definitely look at 76e3fdeab5a7d32e25518d39991b7091f22a4ee6 it adds a `load_supermodule` function to `ModuleAdministrator` that reduces much of my boiler plate.  It makes it so that supermodules can include an `initialize` function in their `__init__.py` files that will be called automatically.

Although a somewhat moot point, by doing it this way (`ModuleAdministrator` calls `initialize`) instead of something like

```.py
import my_psr_supermodule
my_psr_supermodule.initialize(mm)
```
we avoid the need to import the supermodule directly into the input script.  I also take that opportunity to
cache the supermodule instance so you don't have to find it again for each call to load_module (although this hasn't been an issue so far).

Basically my SCF loading went from:

```.py
   mm.load_module("pulsar_libint","NuclearElectron","V builder")
    mm.load_module("pulsar_libint","Kinetic","T builder")
    mm.load_module("pulsar_libint","Overlap","S builder")
    mm.load_module("pulsar_libint","ERI","ERI")
    mm.load_module("pulsar_scf","TElectronic","T")
    mm.load_module("pulsar_scf","NuclearElectronic","V")
    mm.load_module("pulsar_scf","F","F")
    mm.load_module("pulsar_scf","G","G")
    mm.load_module("pulsar_scf","HCore","H")
    mm.load_module("pulsar_scf","Overlap","S")
    mm.load_module("pulsar_scf","Orthogonalizer","X")
    mm.load_module("pulsar_scf","CoreDensity","DCore")
    mm.load_module("pulsar_scf","JK","JK")
    mm.load_module("pulsar_scf","SCF","SCF")
    mm.change_option("V","V_INTS_KEY","V builder")
    mm.change_option("T","T_INTS_KEY","T builder")
    mm.change_option("S","S_INTS_KEY","S builder")
    mm.change_option("X","S_KEY","S")
    mm.change_option("H","H_KEYS",["T","V"])
    mm.change_option("G","JK_KEY","JK")
    mm.change_option("F","H_KEY","H")
    mm.change_option("F","G_KEY","G")
    mm.change_option("SCF","F_KEY","F")
    mm.change_option("SCF","S_KEY","S")
    mm.change_option("SCF","H_KEY","H")
    mm.change_option("SCF","X_KEY","X")
    mm.change_option("DCore","H_KEY","H")
    mm.change_option("DCore","S_KEY","S")
    mm.change_option("JK","ERI_KEY","ERI")
```

to:

```.py
    mm.load_supermodule("pulsar_libint")
    mm.load_supermodule("pulsar_scf")
    mm.change_option("PSR_V","V_INTS_KEY","LIBINT_V")
    mm.change_option("PSR_T","T_INTS_KEY","LIBINT_T")
    mm.change_option("PSR_S","S_INTS_KEY","LIBINT_S")
    mm.change_option("PSR_JK","ERI_KEY","LIBINT_ERI")
```

The remaining four `change_options` are there because of a supermodule boundary.

**Comment by bennybp** [comment]
I think that looks ok, at least on first pass. Are the initialize functions loading all of the modules in the supermodule? Thats a little opaque, but I have kicked around the idea of a function to load all modules in a supermodule

**Comment by ryanmrichard** [comment]
It would be up to the supermodule developer to decide what it does.  I'm
using it to load all modules under some default key.

**Comment by ryanmrichard** [comment]
01e0e73 is a bit in the danger zone for my liking, but it seems to work.........

This commit has to do with reconnecting the integral module base types after the API switcheroo.  It specifically uses Python's memoryview class to export raw pointers.  That part I understand; what I don't understand is exactly how a memoryview works Python side.  It is my understanding that it's a thin wrapper over a pointer with bounds checking.  If that's the case, we should just be able to set the length of the pointer to a large number and it'll be on the user to ensure they don't go out of bounds (just like a raw pointer).  That said I get funny errors if I try to set the length too big (like max int or max size_t).  For more reasonable lengths like 10,000 all the tests (tests really just ensure that a buffer can go round trip from both Python and C++) pass .  I did notice that for numbers like a million I tended to get a segfault (GDB is useless to me as the segfault is in assembly...).  I'm not sure valgrind would help because if there's a bad read it's in the Python interpreter where all hell breaks loose.  I'll have to read up more on the memoryview class.

On a less scary side the two remaining hurdles for sewing up the integral classes (assuming you're on board with them returning the buffers) are:
- multiple shell quartets
  - Are there now so few calls that allocating a buffer per compute call is ok?.
  - If not, I think we'll need an option like MAX_SHELLS_AT_A_TIME or something to precompute the
    buffer (the max size is then the sum of the square/cube/fourth power of the highest angular momenta)
- Structurally speaking, what does the buffer for a general contraction return look like?  
   - Is it number of contractions by (number of basis functions)^n  (for an n-centered integral)?

I need to the latter because STO-3G is general and needs to be de-generalized for libint.  Looping with our BasisSet instance screws up the counting as the shells no longer line-up with libints.  At the moment I degeneralize the basis before filling our BasisSet, but in practice I think a detail like that should be in the initialize step of the integrals implementation since that's what knows if it supports general contractions or not.

**Comment by ryanmrichard** [comment]
I think we need to add to each module type a `my_hash` function with the same signature as the "compute" function.  Otherwise in recursive nestings of say `MatrixBuilder` higher-level modules have no idea what part of the input they forward to lower modules is used.  More concretely, the module for building the density fitting coefficients, call it module A, needs to call the module which builds (mn|P)-like integrals, call it module B.  They both have the same API so the arguments get forwarded, but A has no way of knowing whether B only used part of the arguments or all of them.

**Comment by ryanmrichard** [comment]
@bennybp this also means you'll need to implement a hash combining function for bphash...

**Comment by bennybp** [comment]
I think github ate my email response. But I have more anyway:

1.) I think I need a more thorough example of what you are trying to do with the hashing. If you are going for what I think you are, it might not be worth the complexity it adds. Calling something with mostly the same inputs (rather than exactly the same inputs) I think would be pretty rare.

2.) I'm still not sold on the idea of returning the buffer from integrals, and I think you are finding out why (mostly the size of the buffer, python interaction). It also allows for the caller to place integrals in specific places (think about the 'smart tensors' or placing them in MCDRAM on KNL or something). Unfortunately, that means you have to copy if you are using libint (although you might be able to replace the pointer in the libint struct?)

3.) I like the idea of the supermodule init, but still think loading all the modules this way is odd. To me at least, it violates the principle of least surprise. I would not be opposed to a separate load_all function (which could probably be implemented in the module administrator by just looping over all the elements in the modinfo).

**Comment by ryanmrichard** [comment]
Yep, pretty sure GitHub hated on your email reply.

Let me try to explain the hash thing more.  Elaborating on DF JK, this works by:
- Get expansion coefficients of electron density in fitting basis set (call this module A)
   - This is done via a call to a Rank3Builder
   - The coefficients are built by contracting the inverted metric with three-center two-electron integrals
      - The former is built by a MatrixBuilder (call this module B)
      - The latter by another Rank3Builder (call this module C)
- Contract these coefficients against MO coefficients
- Return J and K

The JK builder is a MatrixBuilder.  Rank3Builders and MatrixBuilders have basically the same API: derivative order, wavefunction, basis sets.  Each iteration of the SCF, the JK builder will get a new wavefunction as that's where the MO coefficients are.  Then on each iteration the JK builder will need to pass that new wavefunction to A, which in turn will pass it to two additional modules, B and C.  Mind you, the only module that depends on the new wavefunction is actually JK itself.  So you say, that's fine; when A gets the new wavefunction, A will realize these changes do not affect it and return the cached coefficients and everything is hunky dory.  But there's the problem A can't know that the changed wavefunction won't change it because A passes that wavefunction to B and C.  So without knowing that B and C are also not changed by the wavefunction, A can't assume anything.  If we let A call B and C again we have to redo a fairly large tensor contraction.  We need A to realize that the changed wavefunction doesn't change B and C.  This is where the hash solution comes in.  Now A calls B's and C's hash function, sees the hash is the same, and just returns the cached result.  As an added bonus this is all automated (basically the check can be moved into the core, see `MatrixBuilder.hpp` for example).

Let's switch back to passing the buffer.  That's the more standard way anyways.  If it's ok with you (or unless you want to use some crazy git-fu), I'd rather accept this PR and then reverse that aspect with another commit.

To me it's not so surprising as without some initial modules, there's not a logical default value for many of the options.  To me this init function is a constructor for the super module and loading these initial modules is simply initialization in the same way that zeroing out an array in a constructor is getting it ready.

**Comment by ryanmrichard** [comment]
Oh.  I guess you don't need a hash combiner because I just made the return type a string.

**Comment by bennybp** [comment]
Ok I see where you are going with the hashing. This mostly comes into play since (most) integrals won't depend on the wavefunction (but some may, ie density-based screening or something). Let me think if there is another way, and think about if the hash type should be a string or the usual vector.

Yeah you can commit the integral buffer changes, then change them back. That should be ok.

For the module initialization: I suppose my concern is what happens when two supermodules are initialized but have the same keys defined (ie, will error, but is not readily fixable by an end user). Also, what happens when a supermodule needs initialization (for some reason), but the user doesn't want to load all modules.

**Comment by ryanmrichard** [comment]
It comes into play a lot more than that.  The wavefunction object contains a plethora of members and is (at the moment) part of many APIs.  So anytime you get a module stack three-deep, with each module taking a wavefunction, you run into this problem.  To avoid this hash thing, I think the other options are:
- Introduce a lot more module types (integral that needs system, integral that only needs basis set, integral that needs system and basis set; basically strip the API down to where no extra information is being passed) or, 
- Hash the results of each submodule before determining whether you need to recompute your module's
  quantity
  - For the DF example above realize that this means likely having to actually compute module C again (or pull the result from disk) as the result of module A and module C are large rank 3 tensors so both fitting in memory simultaneously is going to be rare (as I've already learned while profiling....)

We can chat about the initialization thing tomorrow.

**Pull request merged**
