### PR TITLE
New ghost

### PR DESCRIPTION
**Pull request by ryanmrichard**
# Description of Pull Request
I changed how @bennybp was handling ghost, charge, and dummy atoms.  Specifically, I now use negative Zs for ghosts that way the Z information is not lost.  The dummy and charge Zs are now pushed to -999 and 999 respectively.  Seeing as how it is believed that there can only exist elements up to about Z=173 I think those values should suffice.  I have also modified the get X from  Z functions accordingly.

# Please verify the following:

- [x] Your code does not contain Fortran

## C++ Related Conventions
- [x] Your code is const correct
- [x] Your code is in a namespace

### CODE REVIEW

**Comment by bennybp** [comment]
Works for me, however you need to re-run the script for the LUTs. The new Z numbers haven't propagated from the changes in ElementNames.txt

**Comment by ryanmrichard** [comment]
With the exception of the dummy atom's masses not showing up, I think the scripts are now working.

**Comment by bennybp** [comment]
Dummy masses look to be there. The diff displays it a little weird, if that's what you're looking at

**Comment by ryanmrichard** [comment]
I was looking at my IDE, which apparently did not update after generating the files externally.  You're right that they are in the actual commit though.  I'm going to go ahead and pull this in then.

**Pull request merged**
