### PR TITLE
System test

### PR DESCRIPTION
**Pull request by ryanmrichard**
- Features:
  - Cleans up system class dramatically
    - Macros for boiler-plate
    - Getters/Setters removed
  - Commented out a few functions that weren't being used

### CODE REVIEW

**Comment by ryanmrichard** [comment]
- The only C++ namespaces remaining are pulsar and detail
   - Moving on to Python namespaces after this comment
- The tests are all now comparing generated hashes and not hard-coded ones
- I now have a warning free debug build with g++

**Comment by ryanmrichard** [comment]
- And Python now mirrors C++ with regards to namespaces

**Comment by bennybp** [comment]
Nice. If you are done I can add some comments on the changes

**Comment by ryanmrichard** [comment]
I've got one last tweak to do, but otherwise yeah I'm done.  The last tweak is modifying the scripts that generate the lut and atom data so they don't put the inner namespaces anymore.

**Comment by ryanmrichard** [comment]
That should do it.  I'm now playing with the StandardModules (actually compile, one library, make tests, etc.).

**Comment by ryanmrichard** [comment]
I'll do it later, but I just realized my code examples in the documentation need tweaked now...

**Comment by bennybp** [comment]
Yeah, no need to kill yourself with writing documentation at the moment.
Just hitting the main points is more than a lot of packages have,
particularly at this stage.

-- 
Ben Pritchard
ben@bennyp.org

**Pull request merged**
