### PR TITLE
Updates test documentation and adds NMerInfo test

### PR DESCRIPTION
**Pull request by ryanmrichard**
DOES NOT WORK!!!!!!!!!!!!!!!!!!!!!!

This PR updates the test documentation to be consistent with @bennybp 's changes and adds a test for the NMerInfo class.  The Python version of this test fails (on my system at least) with a double free on the shared pointer.  This is the same issue I'm getting in StandardModules.

### CODE REVIEW

**Comment by ryanmrichard** [comment]
I can verify that switching the export of the `NMerInfo` class so that the `nmer` member is accessed via getters and setters fixes the problem.  This suggests the problem is with how Pybind11 auto generates these functions.

**Comment by ryanmrichard** [comment]
Interestingly it appears that it is the getter that is needed.  I can use the setter provided by `def_readwrite`

**Comment by bennybp** [comment]
I've noticed the bug occurs with a very minimal script that just gets the nmer member:

    import pulsar as psr

    def run_test():
        NI1=psr.NMerInfo()
        print(NI1.nmer)

It's not a double free as I first thought, but something is still going wrong with the delete

**Comment by ryanmrichard** [comment]
I was trying to make a MWE, with a class that contained another class, but I wasn't getting the bug to manifest that way.

**Comment by bennybp** [comment]
Try splitting them up between two compilation units like we have. I've been worried that might be the problem

**Comment by ryanmrichard** [comment]
It's not the cleanest MWE (I didn't want to worry about a build system etc.), but here's what I tried:

This is a new file called `TestA.hpp`:
~~~{.cc}
#pragma once
struct TestA{
  TestA()=default;
   int x;
}
~~~

This is then inside modulebase/export.cpp

~~~{.cc}
//Includes and stuff
#include "TestA.hpp"
namespace pulsar{
void export_modulebase(pybind11::module & m)
{
    pybind11::class_<TestA> (m,"TestA")
    .def(pybind11::init<>())
    .def_readwrite("x",&TestA::x)
    ;
//rest of file
~~~

This is inside `math/export.cpp`:

~~~{.cc}
//Top of file
#include "TestA.hpp"
namespace pulsar{
struct TestB{
   TestB()=default;
   TestA myA;
}

void export_mat(pybind11::module& m)
pybind11::class_ <TestB> (m,"TestB")
.def(pybind11::init<>())
.def_readwrite("myA",&TestB::myA)
;
//Rest of file
~~~

Then in the test file:

~~~{.py}
import pulsar as psr

def run_test():
    anA=psr.TestA()
    anA.x=3

    aB=psr.TestB()
    aB.myA=anA
    print(aB.myA)
~~~

Test works (*i.e.* no segfault)

**Comment by bennybp** [comment]
Only difference I see is that you are missing the shared_ptr holder for TestA

(I did try putting the PYBIND11_DECLARE_HOLDER in the export with the nmer stuff but it didn't seem to affect it)

**Comment by ryanmrichard** [comment]
I tried the `shared_ptr` after I posted the above and it still works.

**Comment by ryanmrichard** [comment]
I withdraw my previous statement, the `shared_ptr` as `TestA`'s holder type does break it, but it does so during Py_Finalize, which I wasn't letting it get to before.

**Comment by bennybp** [comment]
if you put both the exports in the same file does it work? If not that would be a pybind11 bug, I would think

**Comment by ryanmrichard** [comment]
It appears that putting them in the same file also generates the error (the error seemingly is the `shared_ptr` holder type).  I am literally trying to package up a MWE decoupled from Pulsar at the moment.

**Comment by ryanmrichard** [comment]
This should be a minimal working set of files (assuming you have Pybind11-source in the same folder as the following files):

A CMakeLists.txt:
```.sh
project(MWE)
cmake_minimum_required(VERSION 3.0)
include(ExternalProject)
set(CMAKE_CXX_FLAGS "-std=c++11")

find_package(PythonInterp 3.5 REQUIRED)
find_package(PythonLibs 3.5 REQUIRED)

ExternalProject_Add(pybind11_external
    SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/pybind11
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/pybind11
               -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
               -DPYTHON_LIBRARY=${PYTHON_LIBRARY}
               -DPYTHON_INCLUDE_DIR=${PYTHON_INCLUDE_DIR}
               -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE}
               -DPYBIND11_PYTHON_VERSION=3.5
               -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
               -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
               -DPYBIND11_INSTALL=True
               -DPYBIND11_TEST=False
     INSTALL_COMMAND make install DESTDIR=${CMAKE_BINARY_DIR}/stage
)
add_library(MWE SHARED main.cpp)
set(PATH2PYBIND11 ${CMAKE_BINARY_DIR}/stage/usr/local/pybind11/include/)
target_include_directories(MWE PRIVATE ${PATH2PYBIND11} ${PYTHON_INCLUDE_DIRS})
SET_TARGET_PROPERTIES(MWE PROPERTIES PREFIX "")
add_dependencies(MWE pybind11_external)
```

The C++ file
```.cpp
#include <pybind11/pybind11.h>
#include <pybind11/attr.h>
#include <pybind11/cast.h>
#include <pybind11/chrono.h>
#include <pybind11/common.h>
#include <pybind11/complex.h>
#include <pybind11/descr.h>
#include <pybind11/eval.h>
#include <pybind11/functional.h>
#include <pybind11/numpy.h>
#include <pybind11/operators.h>
#include <pybind11/pytypes.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <pybind11/typeid.h>
#include <memory>

PYBIND11_DECLARE_HOLDER_TYPE(T__,std::shared_ptr<T__>)

struct TestA{
    TestA()=default;
    int x;
};

struct TestB{
    TestB()=default;
    TestA myA;
};

PYBIND11_PLUGIN(MWE) {
    pybind11::module m("MWE");

    pybind11::class_<TestA,std::shared_ptr<TestA>> (m,"TestA")
    .def(pybind11::init<>())
    .def_readwrite("x",&TestA::x)
    ;

    pybind11::class_<TestB> (m,"TestB")
    .def(pybind11::init<>())
    .def_readwrite("myA",&TestB::myA);

    return m.ptr();
}
```

The Python test file
```.py
from build.MWE import *

anA=TestA()
anA.x=2
aB=TestB()
aB.myA=anA
print(aB.myA)
```

**Comment by bennybp** [comment]
Yeah that seems like a pybind11 bug to me. I can collect a bit more info and report it in a bit

**Comment by bennybp** [comment]
Ok I think I see what the problem is: See https://github.com/pybind/pybind11/issues/543

**Comment by ryanmrichard** [comment]
I pushed the few other tweaks I made in the debugging process to this branch, it now also removes the macros in the `system.cpp`, I decided I agree with you the clarity is worth the extra lines.

**Comment by bennybp** [comment]
Should be fixed in pybind11 master if you want to try updating. I think there is another change with static members that need to be updated too

On December 6, 2016 3:50:37 PM EST, Ryan Richard <notifications@github.com> wrote:
>This should be a minimal working set of files (assuming you have
>Pybind11-source in the same folder as the following files):
>
>A CMakeLists.txt:
>```.sh
>project(MWE)
>cmake_minimum_required(VERSION 3.0)
>include(ExternalProject)
>set(CMAKE_CXX_FLAGS "-std=c++11")
>
>find_package(PythonInterp 3.5 REQUIRED)
>find_package(PythonLibs 3.5 REQUIRED)
>
>ExternalProject_Add(pybind11_external
>    SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/pybind11
>    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/pybind11
>               -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
>               -DPYTHON_LIBRARY=${PYTHON_LIBRARY}
>               -DPYTHON_INCLUDE_DIR=${PYTHON_INCLUDE_DIR}
>               -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE}
>               -DPYBIND11_PYTHON_VERSION=3.5
>               -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
>               -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
>               -DPYBIND11_INSTALL=True
>               -DPYBIND11_TEST=False
>     INSTALL_COMMAND make install DESTDIR=${CMAKE_BINARY_DIR}/stage
>)
>add_library(MWE SHARED main.cpp)
>set(PATH2PYBIND11
>${CMAKE_BINARY_DIR}/stage/usr/local/pybind11/include/)
>target_include_directories(MWE PRIVATE ${PATH2PYBIND11}
>${PYTHON_INCLUDE_DIRS})
>SET_TARGET_PROPERTIES(MWE PROPERTIES PREFIX "")
>add_dependencies(MWE pybind11_external)
>```
>
>The C++ file
>```.cpp
>#include <pybind11/pybind11.h>
>#include <pybind11/attr.h>
>#include <pybind11/cast.h>
>#include <pybind11/chrono.h>
>#include <pybind11/common.h>
>#include <pybind11/complex.h>
>#include <pybind11/descr.h>
>#include <pybind11/eval.h>
>#include <pybind11/functional.h>
>#include <pybind11/numpy.h>
>#include <pybind11/operators.h>
>#include <pybind11/pytypes.h>
>#include <pybind11/stl.h>
>#include <pybind11/stl_bind.h>
>#include <pybind11/typeid.h>
>#include <memory>
>
>PYBIND11_DECLARE_HOLDER_TYPE(T__,std::shared_ptr<T__>)
>
>struct TestA{
>    TestA()=default;
>    int x;
>};
>
>struct TestB{
>    TestB()=default;
>    TestA myA;
>};
>
>PYBIND11_PLUGIN(MWE) {
>    pybind11::module m("MWE");
>
>    pybind11::class_<TestA,std::shared_ptr<TestA>> (m,"TestA")
>    .def(pybind11::init<>())
>    .def_readwrite("x",&TestA::x)
>    ;
>
>    pybind11::class_<TestB> (m,"TestB")
>    .def(pybind11::init<>())
>    .def_readwrite("myA",&TestB::myA);
>
>    return m.ptr();
>}
>```
>
>The Python test file
>```.py
>from build.MWE import *
>
>anA=TestA()
>anA.x=2
>aB=TestB()
>aB.myA=anA
>print(aB.myA)
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pulsar-chem/Pulsar-Core/pull/25#issuecomment-265268138

-- 
Benjamin Pritchard
ben@bennyp.org

**Comment by ryanmrichard** [comment]
Well the new Pybind11 fix fixes `TestNMerInfo.py`, but breaks `RunTest_BasicModules.py`, which now segfaults at the end in `std::unique_ptr`.  This almost looks like the ol' module is still open problem, but `RunTest.py` calls finalize...

**Comment by bennybp** [comment]
That definitely is the problem. Python is waiting until the end to GC for some reason (or pybind11 has an outstanding copy somewhere).

I will think about a more permanent solution to this. modulemanager should keep track of outstanding modules so it can delete them. I have an idea of how to do this safely.

**Comment by ryanmrichard** [comment]
In my freetime between compilings I've started a symmetry page in the documentation, which contains my notes as I work through that paper I sent you.  It's a WIP, but thought I'd give you a heads up.

**Comment by ryanmrichard** [comment]
Interesting new bug, `RunTest.py` doesn't seem to be correctly detecting failure when the error occurs in a submodule.  I'm looking into it at the moment.

For example here's a snippet from a failed `system_fragmenter` test:
~~~
  1 : FAILED : Resulting water dimer fragments are correct
Caught exception in test
'pulsar.pulsar_core.System' object is not callable

  2 : FAILED : Ethane fragmented correctly


================================================================================
RESULTS: 2 failed
================================================================================


ModuleManager has no modules in use
Looking to close C++ supermodule ###
Supermodule ### doesn't have finalization function. Skipping
Closed supermodule ###
Finalizing parallelization
Finalizing process 0 of 1
<end of output>
Test time =   0.21 sec
----------------------------------------------------------
Test Passed.
~~~

**Comment by bennybp** [comment]
Is the run_test function returning the number of failed tests? That's how it is done in the core (rather than through exceptions)

**Comment by ryanmrichard** [comment]
That's the problem... Thanks.

**Comment by bennybp** [comment]
Any objection to merging/resolving this for now?

**Pull request merged**
