### PR TITLE
WIP: Build polishing #1

### PR DESCRIPTION
**Pull request by bennybp**
(WIll not build right now due to local path for LTF)

After this will be another PR with more build cleaning and polishing, but I'd like this to be separate due to the magnitude of the changes

* Makes C++14 the default standard
* Removes external projects from source tree
* Updates pybind11
* Updates bphash, bpprint with C++14
* Some small build cleaning

Todo
- [x] Merge in other changes from PR #27

### CODE REVIEW

**Comment by ryanmrichard** [comment]
lol at -25,000 lines of code

**Comment by bennybp** [comment]
Ok I would like to merge this before continuing to butcher the build stuff.  I'm interested in seeing if this breaks any of your StandardModule or psi4 module changes. I tried to make it so it wouldn't, but that usually doesn't mean anything.

**Comment by ryanmrichard** [comment]
Just merge it.  My builds are all f-d up between the Pybind11 changes and the Psi4 (re-?)re-rewrite of the CMake build.  I'm at the moment waiting for things to simmer down before going back to getting StandardModule and Psi4 working again.

**Comment by bennybp** [comment]
Yeah I hear you on that

**Pull request merged**
