### PR TITLE
Move python helper stuff to util and condense

### PR DESCRIPTION
**Pull request by bennybp**
With pybind11 now handling exceptions, there's very little that is
needed for python helpers. All the functionality can be condensed into a
single header file with ~120 LOC. Other minor changes were needed w.r.t. mangling

### CODE REVIEW

**Comment by ryanmrichard** [comment]
Are the Python tests like TestMathSet.py working for you?  I'm getting segfaults at the end of most of the python tests now.  I'm not loading any pulsar modules so I don't think it's our typical segfault from having a module open.

```
#0  0x00007ffff786f4f5 in malloc_consolidate (
    av=av@entry=0x7ffff7bb4b20 <main_arena>) at malloc.c:4184
#1  0x00007ffff787255e in _int_malloc (
    av=av@entry=0x7ffff7bb4b20 <main_arena>, bytes=bytes@entry=12320)
    at malloc.c:3451
#2  0x00007ffff78745a4 in __GI___libc_malloc (bytes=12320) at malloc.c:2914
#3  0x00000000005a2eda in ?? ()
#4  0x00000000005aba1c in PyDict_Merge ()
#5  0x00000000005abd9b in PyDict_Copy ()
#6  0x0000000000527bfa in PyImport_Cleanup ()
#7  0x00000000005fee1e in Py_Finalize ()
#8  0x000000000063fa74 in Py_Main ()
#9  0x00000000004d00e1 in main ()
```

**Comment by ryanmrichard** [comment]
Valgrind is only coming back with python errors for me.

**Comment by bennybp** [comment]
They are working for me. Was this before of after this merge?

-- 
Ben Pritchard
ben@bennyp.org

**Comment by ryanmrichard** [comment]
I just rebased from master; I've also blown away install/build.  I'll try a fresh clone.  After rebasing, but before the clean build, I updated my system so I'm hoping I didn't get a bummed version of python....

**Comment by ryanmrichard** [comment]
Yeah a fresh version doesn't gives me the same errors.

**Comment by ryanmrichard** [comment]
*does.  It does give me the same errors.

**Comment by ryanmrichard** [comment]
Just recompiled with Intel and all works.  This appears to be a GCC bug.

**Comment by bennybp** [comment]
Wonderful. I'll see if I can reproduce and hunt it down

**Comment by bennybp** [comment]
Still seems to work for me with gcc 4.9.3 and 5.3.1

**Comment by ryanmrichard** [comment]
Interesting.  I have 5.4 though.

**Pull request merged**
